# Generated by Django 5.1.7 on 2025-03-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
