# Generated by Django 5.1.7 on 2025-03-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_portfolio_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='view_count',
        ),
    ]
